import sys, os, glob
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Map các chuỗi bị corrupt sang tiếng Việt đúng
# (sắp xếp chuỗi dài trước để tránh bị replace từng phần)
fixes = [
    # Cụm từ dài, có thể có khoảng trắng
    ("T?o �on h�ng", "Tạo đơn hàng"),
    ("B?ng c?a (?nh, t�n, d�ng c�nh, � ch?, ph�t sinh, SL, don gi�, th�nh ti?n).", "Bảng cửa (ảnh, tên, dòng cánh, ô chờ, phát sinh, SL, đơn giá, thành tiền)."),
    ("Quay l?i", "Quay lại"),
    ("Th�ng tin kh�ch h�ng", "Thông tin khách hàng"),
    ("T? d?ng luu khi t?o don � d�ng l?i cho l?n sau", "Tự động lưu khi tạo đơn - dùng lại cho lần sau"),
    ("M� KH (t? sinh)", "Mã KH (tự sinh)"),
    ("H? t�n", "Họ tên"),
    ("S? di?n tho?i", "Số điện thoại"),
    ("�?a ch?", "Địa chỉ"),
    ("G� t�n ho?c S�T d? t�m kh�ch cu. N?u chua c�, d? tr?ng � h? th?ng s? t? luu m?i khi t?o don.", "Gõ tên hoặc SĐT để tìm khách cũ. Nếu chưa có, để trống - hệ thống sẽ tự lưu mỗi khi tạo đơn."),
    ("B?ng c?a", "Bảng cửa"),
    ("Ng�y ", "Ngày "),
    ("Kh�ch: ", "Khách: "),
    ("T�n kh�ch + M� t? sinh", "Tên khách + Mã tự sinh"),
    ("D�ng c�nh", "Dòng cánh"),
    ("K.thu?c � ch? (R�C�D)", "K.thước ô chờ (RxCxD)"),
    ("Ph�t sinh gia c�ng", "Phát sinh gia công"),
    ("�on gi�", "Đơn giá"),
    ("Th�nh ti?n", "Thành tiền"),
    ("Th�m d�ng c?a", "Thêm dòng cửa"),
    ("Chua c� d�ng c?a n�o. Nh?n \"Th�m d�ng c?a\" d? b?t d?u.", "Chưa có dòng cửa nào. Nhấn \"Thêm dòng cửa\" để bắt đầu."),
    ("B?ng ph? ki?n & d?ch v?", "Bảng phụ kiện & dịch vụ"),
    ("Lo?i / T�n s?n ph?m", "Loại / Tên sản phẩm"),
    ("Quy c�ch", "Quy cách"),
    ("Th�m ph? ki?n / d?ch v?", "Thêm phụ kiện / dịch vụ"),
    ("Chua c� ph? ki?n/d?ch v? n�o. C� th? b? qua.", "Chưa có phụ kiện/dịch vụ nào. Có thể bỏ qua."),
    ("B?n l?", "Bản lề"),
    ("L?p d?t", "Lắp đặt"),
    ("V?n chuy?n", "Vận chuyển"),
    ("Tr?ng th�i & Ghi ch�", "Trạng thái & Ghi chú"),
    ("Tr?ng th�i", "Trạng thái"),
    ("Ghi ch� th�m...", "Ghi chú thêm..."),
    ("Upload ?nh", "Upload ảnh"),
    ("Ch?n ph�t sinh...", "Chọn phát sinh..."),
    ("X�a d�ng", "Xóa dòng"),
    ("T�n s?n ph?m / d?ch v?", "Tên sản phẩm / dịch vụ"),
    ("Quy c�ch / M� t?", "Quy cách / Mô tả"),
    ("T?ng c?ng:", "Tổng cộng:"),
    ("X�a d�ng c?a n�y?", "Xóa dòng cửa này?"),
    ("X�a d�ng n�y?", "Xóa dòng này?"),
    ("T�m theo t�n ph�t sinh (v� d?: kh�a, k�nh, l?p d?t...)", "Tìm theo tên phát sinh (ví dụ: khóa, kính, lắp đặt...)"),
    ("Ch?n ph�t sinh gia c�ng", "Chọn phát sinh gia công"),
    ("Kh�ng c� ph�t sinh n�o ph� h?p v?i \"", "Không có phát sinh nào phù hợp với \""),
    ("Kh�ng c� ph�t sinh n�o", "Không có phát sinh nào"),
    ("Chua c� ph�t sinh n�o.", "Chưa có phát sinh nào."),
    ("�� ch?n:", "Đã chọn:"),
    ("Th�m ph�t sinh", "Thêm phát sinh"),
    ("Th�m ngay", "Thêm ngay"),
    ("H?y", "Hủy"),
    ("T?o don h�ng", "Tạo đơn hàng"),
    ("T?o don ", "Tạo đơn "),
    ("th�nh c�ng!", "thành công!"),
    ("Upload l?i: ", "Upload lỗi: "),
    ("Vui l�ng nh?p t�n kh�ch h�ng", "Vui lòng nhập tên khách hàng"),
    ("Vui l�ng nh?p s? di?n tho?i", "Vui lòng nhập số điện thoại"),
    ("Vui l�ng th�m �t nh?t 1 d�ng s?n ph?m", "Vui lòng thêm ít nhất 1 dòng sản phẩm"),
    ("(M� t? sinh)", "(Mã tự sinh)"),
    ("(S? t? di?n t? th�ng tin kh�ch)", "(Sẽ tự điền từ thông tin khách)"),
    ("T? sinh", "Tự sinh"),
    ("d�ng c?a", "dòng cửa"),
    ("ph? ki?n / DV", "phụ kiện / DV"),
    ("b? (t?ng SL)", "bộ (tổng SL)"),
    ("b? c?a", "bộ cửa"),
    ("Kh�c", "Khác"),
    ("Kh�a", "Khóa"),
    ("K�nh", "Kính"),
    ("Chi?c", "Chiếc"),
    ("c�i", "cái"),
    ("b?", "bộ"),
    ("l?n", "lần"),
    ("m�", "mét"),
    ("T?o don h�ng", "Tạo đơn hàng"),
    ("?nh", "Ảnh"),
    ("Hình", "Hình"),
    ("Loại", "Loại"),
    ("Tên", "Tên"),
    ("Sản phẩm", "Sản phẩm"),
    ("Kích thước", "Kích thước"),
    ("Vui lòng", "Vui lòng"),
    ("nhập", "nhập"),
    ("Đơn", "Đơn"),
    ("giá", "giá"),
    ("Thành", "Thành"),
    ("tiền", "tiền"),
    ("Tên khách", "Tên khách"),
    ("Dòng", "Dòng"),
    ("Phát", "Phát"),
    ("sinh", "sinh"),
    ("Quy", "Quy"),
    ("cách", "cách"),
    ("Số", "Số"),
    ("lượng", "lượng"),
    ("Hủy", "Hủy"),
    ("Upload", "Upload"),
    ("Đang", "Đang"),
    ("Lỗi", "Lỗi"),
    ("Đã", "Đã"),
    ("chọn", "chọn"),
    ("phù", "phù"),
    ("hợp", "hợp"),
    ("với", "với"),
    ("Tìm", "Tìm"),
    ("theo", "theo"),
    ("tên", "tên"),
    ("Lắp", "Lắp"),
    ("đặt", "đặt"),
    ("Vận", "Vận"),
    ("chuyển", "chuyển"),
    ("Bản", "Bản"),
    ("lề", "lề"),
    ("Xóa", "Xóa"),
    ("dòng", "dòng"),
    ("Thêm", "Thêm"),
    ("Phụ", "Phụ"),
    ("kiện", "kiện"),
    ("Dịch", "Dịch"),
    ("vụ", "vụ"),
    ("Trạng", "Trạng"),
    ("thái", "thái"),
    ("Ghi", "Ghi"),
    ("chú", "chú"),
    ("thêm", "thêm"),
    ("Quay", "Quay"),
    ("lại", "lại"),
    ("Thông", "Thông"),
    ("tin", "tin"),
    ("khách", "khách"),
    ("hàng", "hàng"),
    ("Mã", "Mã"),
    ("tự", "tự"),
    ("Họ", "Họ"),
    ("tên", "tên"),
    ("Điện", "Điện"),
    ("thoại", "thoại"),
    ("Địa", "Địa"),
    ("chỉ", "chỉ"),
    ("Gõ", "Gõ"),
    ("hoặc", "hoặc"),
    ("SĐT", "SĐT"),
    ("để", "để"),
    ("tìm", "tìm"),
    ("cũ", "cũ"),
    ("Nếu", "Nếu"),
    ("chưa", "chưa"),
    ("có", "có"),
    ("trống", "trống"),
    ("hệ", "hệ"),
    ("thống", "thống"),
    ("sẽ", "sẽ"),
    ("lưu", "lưu"),
    ("mỗi", "mỗi"),
    ("khi", "khi"),
    ("tạo", "tạo"),
    ("đơn", "đơn"),
    ("Tự", "Tự"),
    ("động", "động"),
    ("dùng", "dùng"),
    ("lần", "lần"),
    ("sau", "sau"),
    ("Bảng", "Bảng"),
    ("cửa", "cửa"),
    ("ảnh", "ảnh"),
    ("cánh", "cánh"),
    ("ô", "ô"),
    ("chờ", "chờ"),
    ("kích", "kích"),
    ("thước", "thước"),
    ("gia", "gia"),
    ("công", "công"),
    ("cộng", "cộng"),
    ("Tổng", "Tổng"),
    ("ít", "ít"),
    ("nhất", "nhất"),
    ("Tạo", "Tạo"),
    ("thành", "thành"),
    ("công", "công"),
]

# Loại bỏ trùng & sort theo độ dài giảm dần
seen = set()
unique = []
for src, dst in fixes:
    if src not in seen:
        seen.add(src)
        unique.append((src, dst))
unique.sort(key=lambda x: -len(x[0]))

def fix_file(path):
    raw = open(path, "rb").read()
    text = raw.decode("utf-8", errors="replace")
    orig = text
    cnt = 0
    for src, dst in unique:
        if src in text:
            n = text.count(src)
            text = text.replace(src, dst)
            cnt += n
            print(f"  {n}x: {src!r} -> {dst!r}")
    if text != orig:
        open(path, "w", encoding="utf-8", newline="").write(text)
    return cnt

base = "d:/LUMI-HOME/qldhjava/src/main/resources/templates"
files = [
    "orders/create-multi.html",
    "orders/detail.html",
    "admin/product-specs.html",
    "production/material-summary.html",
    "dashboard.html",
]
for f in files:
    p = os.path.join(base, f)
    if os.path.exists(p):
        print("=== ", f, "===")
        n = fix_file(p)
        print(f"   total replacements: {n}")
        print()